### ISSUE TITLE
ERROR: (eagle-rc.c:149: errno: None) bad fields in EAGLE read info file

### ISSUE THREAD

**Issue by cjy8709** [tony-kuo/eagle#1]
Dear, Tony

I've been playing around with the eagle pipeline also following the example script for an allopolyploid case I have. Its not exactly an allopolyploid, but I have an F1 hybrid transcriptome data set and have both parents reference genome.
I got upto the step 

eagle-rc -a data_align2_A.bam --listonly -o Ref_A.sample Ref_A.sample.txt Ref_A.sample.readinfo.txt > Ref_A.sample.list

But get the following error

ERROR: (eagle-rc.c:149: errno: None) bad fields in EAGLE read info file

I can send some of the files I've generated to get to the step if you want as well.

Sincerely,

Jae

**Comment by cjy8709** [comment]
Hi Tony

Sorry I should have said that I tried the -v switch and got the error message. 
Without the -v switch I get the error message:

> Missing EAGLE output file!

Jae

**Comment by tcykuo** [comment]
Hi Jae,

Thanks for the data.  The issue was the flag field was empty as that is valid when using single-end reads.  I've solved the issue and updated the code.

I also suggest you try the --ngi mode to perhaps simplify your workflow, though it doesn't have the advantage of using explicit genotype information as in the default workflow.
