### ISSUE TITLE
Question: EAGLE-RC suitable for long-read RNA-seq?

### ISSUE THREAD

**Issue by nadjano** [tony-kuo/eagle#7]
Hello, 

EAGLE-RC seems like a very useful tool for Allele specific expression. 

I saw the option `--dp`. So with this is can run EAGLE-RC on aligned long-read RNA-seq (e.g IsoSeq)?
Or do you have any other recommendation of parameters for analysing long-read RNA-seq?

Thank you! 

Best, 
Nadja

**Comment by tony-kuo** [comment]
Hi Nadja,

Indeed `--dp` is used for long RNA-seq reads, specifically those with higher base-calling error rates / indel error rates such as PacBio sequencing.

Other parameters you should be aware of are:

`--gap_op` [INT] Gap open penalty for use with --dp. Default is 6. For long reads that contain indel errors, 2 may be a better.

`--gap_ex` [INT] Gap extend penalty for use with --dp. Default is 1.

`--lowmem` should not be used

`--rc' should not be used because it includes `--lowmem`

As you're planning to use EAGLE-RC. I would perhaps suggest:

`--omega=1.0e-40 --isc --mvh --verbose --dp`

and optionally consider changing the gap open penalty to be lower.

Note that this will preclude you from using `--ngi` in `eagle-rc`.

Hope this helps.

**Comment by nadjano** [comment]
Thanks a lot for the suggestions and the quick response! That is very helpful! 😃
